# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bd5e6706ee9150a6cc97a4551bff8247"
name = "Section_Store"
handle = "section_store"
application_url = "https://vietnam-securities-lithuania-deer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "novaanestt.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://vietnam-securities-lithuania-deer.trycloudflare.com/auth/callback",
  "https://vietnam-securities-lithuania-deer.trycloudflare.com/auth/shopify/callback",
  "https://vietnam-securities-lithuania-deer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
